server.port=8080
server.servlet.context-path=/focus-flow
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=focus_flow;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
